<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Tanyas-MacBook-Air.local" ignored="0" name="AdditionSubtractionTest" tests="35" failures="6" timestamp="13 Dec 2017 20:22:46 GMT" time="0.241" errors="0">
  <testcase name="sumNegativeLongs" time="0.012" classname="com.epam.testng.tests.SumDoublesTest"/>
  <testcase name="sumNegativeLongs" time="0.002" classname="com.epam.testng.tests.SumDoublesTest"/>
  <testcase name="sumNegativeLongs" time="0.001" classname="com.epam.testng.tests.SumDoublesTest"/>
  <testcase name="sumPositiveAndNegativeLongs" time="0.003" classname="com.epam.testng.tests.SumDoublesTest">
    <failure type="java.lang.AssertionError" message="Invalid operation result expected [4.56] but found [4.560000000000002]">
      <![CDATA[java.lang.AssertionError: Invalid operation result expected [4.56] but found [4.560000000000002]at com.epam.testng.tests.SumDoublesTest.sumPositiveAndNegativeLongs(SumDoublesTest.java:24)... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sumPositiveAndNegativeLongs -->
  <testcase name="sumPositiveAndNegativeLongs" time="0.003" classname="com.epam.testng.tests.SumDoublesTest">
    <failure type="java.lang.AssertionError" message="Invalid operation result expected [2.14748364511E9] but found [2.1474836451100001E9]">
      <![CDATA[java.lang.AssertionError: Invalid operation result expected [2.14748364511E9] but found [2.1474836451100001E9]at com.epam.testng.tests.SumDoublesTest.sumPositiveAndNegativeLongs(SumDoublesTest.java:24)... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- sumPositiveAndNegativeLongs -->
  <testcase name="sumPositiveAndNegativeLongs" time="0.002" classname="com.epam.testng.tests.SumDoublesTest"/>
  <testcase name="sumPositiveLongs" time="0.002" classname="com.epam.testng.tests.SumDoublesTest"/>
  <testcase name="sumPositiveLongs" time="0.002" classname="com.epam.testng.tests.SumDoublesTest"/>
  <testcase name="sumPositiveLongs" time="0.001" classname="com.epam.testng.tests.SumDoublesTest"/>
  <testcase name="sumNegativeLongs" time="0.001" classname="com.epam.testng.tests.SumLongsTest"/>
  <testcase name="sumNegativeLongs" time="0.001" classname="com.epam.testng.tests.SumLongsTest"/>
  <testcase name="sumNegativeLongs" time="0.002" classname="com.epam.testng.tests.SumLongsTest"/>
  <testcase name="sumPositiveAndNegativeLongs" time="0.003" classname="com.epam.testng.tests.SumLongsTest"/>
  <testcase name="sumPositiveAndNegativeLongs" time="0.001" classname="com.epam.testng.tests.SumLongsTest"/>
  <testcase name="sumPositiveAndNegativeLongs" time="0.002" classname="com.epam.testng.tests.SumLongsTest"/>
  <testcase name="sumPositiveLongs" time="0.002" classname="com.epam.testng.tests.SumLongsTest"/>
  <testcase name="sumPositiveLongs" time="0.006" classname="com.epam.testng.tests.SumLongsTest">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: sumPositiveLongs([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])
Arguments: [(java.lang.Long) 9223372036854775807,(java.lang.Long) 9223372036854775807,(java.lang.Double) 1.8446744E19]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: Data provider mismatchMethod: sumPositiveLongs([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])Arguments: [(java.lang.Long) 9223372036854775807,(java.lang.Long) 9223372036854775807,(java.lang.Double) 1.8446744E19]... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sumPositiveLongs -->
  <testcase name="suNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="suNegativeLongs" time="0.002" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="suNegativeLongs" time="0.002" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="subPositiveAndNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="subPositiveAndNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="subPositiveAndNegativeLongs" time="0.002" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="subPositiveLongs" time="0.003" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="subPositiveLongs" time="0.002" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="subPositiveLongs" time="0.004" classname="com.epam.testng.tests.SubDoublesTest"/>
  <testcase name="subNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subPositiveAndNegativeLongs" time="0.002" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subPositiveAndNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subPositiveAndNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subPositiveLongs" time="0.003" classname="com.epam.testng.tests.SubLongsTest">
    <failure type="org.testng.TestException" message="
Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5c3bd550] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.TestException: ... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- subPositiveLongs -->
  <testcase name="subPositiveLongs" time="0.002" classname="com.epam.testng.tests.SubLongsTest">
    <failure type="org.testng.TestException" message="
Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5c3bd550] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.TestException: ... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- subPositiveLongs -->
  <testcase name="subPositiveLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest">
    <failure type="org.testng.TestException" message="
Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5c3bd550] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.TestException: ... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- subPositiveLongs -->
</testsuite> <!-- AdditionSubtractionTest -->
